### ISSUE TITLE
Why was the last version on crates yanked?

### ISSUE THREAD

**Issue by Jasperav** [durch/rust-s3#167]
This crate has tokio 1.0 dependency on the 'dev' branch. Why isn't the dev branch merged with master? Currently I have a dependency on the dev branch. 

I see on crates.io that the last version is yanked: https://crates.io/crates/rust-s3. When will there be a new crates version?

**Comment by durch** [comment]
@Jasperav `beta9` was yanked due to #161. There is a `beta10`, but crates.io sorting hides it from the list :/

`dev` branch will be merged to master, and `0.27` will graduate from beta, there are a few more issues and PRs to address before that, and my schedule has been a bit cramped, I've got some tentative plans to get most of the issues closed this week.

**Comment by Jasperav** [comment]
@durch are there any plans to merge dev to master?

**Comment by durch** [comment]
There sure are, unfortunately I'm a bit strapped for time. Ideally 0.27 will graduate out of beta in the next two weeks
