### ISSUE TITLE
Please, implement Copy operation on structs "Credentials", "Region" 

### ISSUE THREAD

**Issue by poul1x** [durch/rust-s3#202]
**Is your feature request related to a problem? Please describe.**

Look at my code:

```rs
extern crate s3;

use s3::bucket::Bucket;
use s3::creds::Credentials;
use s3::Region;

fn main() {
    let access_key = Some("root");
    let secret_key = Some("toortoor");
    let creds = Credentials::new(access_key, secret_key, None, None, None).unwrap();

    let region_name = "nl-ams".to_string();
    let endpoint = "http://localhost:9000".to_string();
    let region = Region::Custom {
        region: region_name,
        endpoint,
    };

    let bucket_fuzzers = Bucket::new_with_path_style("Fuzzers-dev", region, creds).unwrap();
    let bucket_data = Bucket::new_with_path_style("Data-dev", region, creds).unwrap();

    // let bucket_fuzzers = Bucket::new_with_path_style("Fuzzers-dev", region.clone(), creds.clone()).unwrap();
    // let bucket_data = Bucket::new_with_path_style("Data-dev", region.clone(), creds.clone()).unwrap();

    let (_res, _) = bucket_data.head_object_blocking("/1.txt").unwrap();
    // println!("{:?}", res);

    let (res, _) = bucket_fuzzers.head_object_blocking("/1.txt").unwrap();
    println!("{:?}", res.metadata);
}
```

It does not compile, because `creds` and `region` are moved in first `Bucket::new_with_path_style` call:

![image](https://user-images.githubusercontent.com/31695750/122808968-2d503e80-d2d6-11eb-88ca-92707871b9ef.png)

**Describe the solution you'd like**

Implement `Copy` operation on "Credentials", "Region" and other related structs.

**Describe alternatives you've considered**

Temporary solution:

```rust
    let bucket_fuzzers = Bucket::new_with_path_style("Fuzzers-dev", region.clone(), creds.clone()).unwrap();
    let bucket_data = Bucket::new_with_path_style("Data-dev", region.clone(), creds.clone()).unwrap();
```

I don't like it at all.

**Additional information**:
rust-s3 = "0.26.4"
s3: minio

**Comment by durch** [comment]
@poul1x I completely agree that it would be nicer to have `Copy`, but since `Region` can hold strings, implementing `Copy` is not trivial, not sure when and if this will get done

**Comment by danya02** [comment]
Perhaps such a usage might be cleaner if the functions that create the buckets did not take ownership of the `Region` and `Credentials`? They could instead take a reference to it, and you wouldn't have to pepper the call-site with `.clone()` calls.

The easiest way to do this would be to make the `Bucket` constructor internally clone the passed-in values. A more complicated, but perhaps more descriptive, approach would be to have it hold a reference to the region+credentials, such that the lifetime of a `Bucket` is bounded by the lifetime of those: this makes it clear that in order to use a `Bucket`, you need to have the `Region` and `Credentials` available, but it might make it harder to pass ownership of all these taken together to someone else.
