### ISSUE TITLE
Exposing error in form of `thiserror` instead of `anyhow`

### ISSUE THREAD

**Issue by iamsiddhant05** [durch/rust-s3#260]
**Is your feature request related to a problem? Please describe.**
The error trait is not exposed in the library, which makes it difficult to unwrap and bubble up.

**Describe alternatives you've considered**
An alternate would be if you could expose a custom `RustS3Error` trait for error handling

**Comment by blackghost1987** [comment]
Yeah, this was a bit surprising for me! The `anyhow` crate explicitly states that it should be used for application code and libraries should use `thiserror` instead.
Also my upstream library is using `thiserror` as well, but because of this crate I had to import `anyhow` as well, just so I could encapsulate it with `thiserror`.

This looks like a good first contribution, I'll see if I'll have the time to work on a PR.

**Comment by nightmared** [comment]
In the past, I already tried to add this to rust-s3: https://github.com/durch/rust-s3/pull/166. Maybe this could serve as a useful basis if you desire to implement it and want to get it merged (something I failed to do, given that my PR was closed without explanations?).
In any case, I second the fact that this would be a very useful feature!

**Comment by nightmared** [comment]
Sorry, wrong link, the most recent PR on the matter is https://github.com/durch/rust-s3/pull/189.
